# Generated by Django 5.0 on 2023-12-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_desc', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=30)),
                ('item_img', models.ImageField(upload_to='media')),
                ('item_price', models.IntegerField(null=True)),
            ],
        ),
    ]
