# Generated by Django 5.0 on 2023-12-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='item_img',
        ),
    ]
