# Generated by Django 5.0 on 2023-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_menuitems_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('noOfGuests', models.IntegerField(null=True)),
                ('reservationDate', models.DateField(null=True)),
                ('reservationTime', models.CharField(max_length=30)),
            ],
        ),
    ]
