# Generated by Django 5.0 on 2023-12-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_reservationdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reservationdetails',
            name='lastName',
        ),
    ]
