# Generated by Django 5.0 on 2023-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_firstname_reservationdetails_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
