# Generated by Django 5.0 on 2023-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_reservationdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemQty', models.IntegerField(null=True)),
                ('orderedBy', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('orderStatus', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
    ]
